#!/usr/bin/env bash
set -e

# pip install --no-cache-dir spikeinterface[full]==0.101.0rc1
git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout 1b55388d627d0011acf4fac08d3333b80ad07e13
pip install --no-cache-dir .[full]
cd ..